### ISSUE TITLE
Change the way datasets are imported

### ISSUE THREAD

**Issue by allaffa** [allaffa/GCNN#34]
It would be better if the datasets was specified differently in the configure file. 
Now, we are using numbers to indicate which dataset to use. 
It would be much more convenient if the user specified himself/herself the directory from which the data has to be pulled. 
In particular, I would like to give two options:

- [x] provide only one directory: the dataset is automatically split into training and validation #65 
- [x] explicitly provide two directories: one directory is used to extract the training data, the other one is used to extract the validation data #101

**Comment by allaffa** [comment]
@streeve 

You already took care of this. Correct? If yes, then let's close this issue.

**Comment by streeve** [comment]
You're right - #65 should have been linked here since it added the dataset path to the config file. But we don't have the second option for separate train/validate paths, which would be helpful for #83
