### ISSUE TITLE
Test example config syntax in CI

### ISSUE THREAD

**Issue by streeve** [allaffa/GCNN#70]
#69 shows that simple bugs get through current unit tests

**Comment by streeve** [comment]
We shouldn't run the full example cases (`configuration.json`), but run enough to make sure there aren't mistakes like the one linked in the description

**Comment by allaffa** [comment]
what is this meant for?

**Comment by streeve** [comment]
> what is this meant for?

The linked PR fixed a bug in one of the examples - we should have a test to make sure that doesn't happen again
